# Generated by Django 5.2.8 on 2025-11-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_pengaduan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warga',
            old_name='no_telepon',
            new_name='nomor_telepon',
        ),
        migrations.RenameField(
            model_name='warga',
            old_name='tanggal_regitstrasi',
            new_name='tanggal_registrasi',
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(choices=[('BARU', 'Baru'), ('DIPROSES', 'Dalam Proses'), ('SELESAI', 'Selesai')], default='BARU', max_length=10),
        ),
    ]
